### PR TITLE
Fixed segfault when decoding subtitles

### PR DESCRIPTION
**Pull request by lorenz**
This fixes a segfault in Movian with certain kinds of subtitles because in these cases the `rects` array itself is being allocated, but the individual rects are not.

### CODE REVIEW

**Comment by andoma** [comment]
Hm, this seems to rely on the fact that malloc fails for some certain types of (large) allocations?

Do you have an example file where this is a problem?

**Comment by lorenz** [comment]
Example is quite large, ~10GiB, should I make it available?

**Comment by lorenz** [comment]
Actually the PR ist against the wrong branch. In current libav master, the for loop for allocating is gone (Commit from 2014) and that breaks it. The rebase against this master removed that and only left the patches from the original 2014 commit which deal with memory allocation failures.

**Comment by lorenz** [comment]
I'm closing this PR, as I made one against libav master (**https://github.com/libav/libav/pull/26**), but we should probably backport the fix to whatever branch Movian is using.

**Comment by andoma** [comment]
Check!

**Pull request closed without merging**
